# fly.toml app configuration file generated for email-opened on 2023-05-21T15:23:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "email-opened"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
